version: '3.8'

services:
  minio:
    container_name: minio_server
    image: minio/minio
    build:
      context: ./minio
    volumes:
      - ./minio/data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"

  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    container_name: weaviate_server
    image: semitechnologies/weaviate:latest
    ports:
      - 8080:8080
      - 50051:50051
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      DEFAULT_VECTORIZER_MODULE: 'none'
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_MODULES: 'backup-s3'
      BACKUP_S3_BUCKET: 'weaviate-backups'
      BACKUP_S3_ENDPOINT: 'minio:9000'
      BACKUP_S3_ACCESS_KEY_ID: 'minio'
      BACKUP_S3_SECRET_ACCESS_KEY: 'minio123'
      BACKUP_S3_USE_SSL: 'false'
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - ./weaviate/data:/var/lib/weaviate
    depends_on:
      - minio

  python-app:
    image: cdaprod/python-app
    container_name: python_server
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      USE_SSL: ${USE_SSL}
      WEAVIATE_ENDPOINT: ${WEAVIATE_ENDPOINT}
    restart: unless-stopped
    depends_on:
      - weaviate
      - minio

volumes:
  minio-data:
    driver: local
