version: '3.8'

services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    container_name: weaviate_hydrate
    image: semitechnologies/weaviate:latest
    ports:
      - 8080:8080
      - 50051:50051
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      DEFAULT_VECTORIZER_MODULE: 'none'
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_MODULES: 'backup-s3,text2vec-openai,generative-openai,generative-cohere,generative-palm,ref2vec-centroid,reranker-cohere,qna-openai'
      BACKUP_S3_BUCKET: 'weaviate-backups'
      BACKUP_S3_ENDPOINT: ${MINIO_ENDPOINT}
      BACKUP_S3_ACCESS_KEY_ID: ${MINIO_ACCESS_KEY}
      BACKUP_S3_SECRET_ACCESS_KEY: ${MINIO_SECRET_KEY}
      BACKUP_S3_USE_SSL: ${USE_SSL}
      CLUSTER_HOSTNAME: 'urls1'
    volumes:
      - ../weaviate/data:/var/lib/weaviate