name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      minio:
        image: minio/minio:latest
        ports:
          - 9000:9000
        env:
          MINIO_ROOT_USER: minio
          MINIO_ROOT_PASSWORD: minio123
        options: server /data

      weaviate:
        image: semitechnologies/weaviate:latest
        ports:
          - 8080:8080

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt
          pip install httpx pytest pytest-asyncio

      - name: Run tests
        run: pytest /app/tests/test_api.py